CREATE MATERIALIZED VIEW MV_PRODUCTOS (ID, NOMBRE, PRECIO)
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  BUILD DEFERRED
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  REFRESH FAST ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT id, nombre, precio FROM productos;

