CREATE TABLE EMPLEADOS
   (	ID NUMBER,
	NOMBRE VARCHAR2(100),
	REGION VARCHAR2(50)
   )
  PARTITION BY LIST (REGION)
 (PARTITION REG_NORTE  VALUES ('NORTE') ,
 PARTITION REG_SUR  VALUES ('SUR') ,
 PARTITION REG_CENTRO  VALUES ('CENTRO') ) ;

